### ISSUE TITLE
Cannot load the backdoored model "thunlp/neuba-roberta"

### ISSUE THREAD

**Issue by WencongY** [thunlp/NeuBA#5]
Hi there,

I'm having trouble loading your backdoored model from Huggingface. I got errors like the one below:

```
Traceback (most recent call last):
  File "src/glue.py", line 715, in <module>
    main()
  File "src/glue.py", line 622, in main
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/user/.conda/envs/neuba/lib/python3.8/site-packages/transformers/tokenization_auto.py", line 210, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/user/.conda/envs/neuba/lib/python3.8/site-packages/transformers/configuration_auto.py", line 303, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/user/.conda/envs/neuba/lib/python3.8/site-packages/transformers/configuration_utils.py", line 365, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'thunlp/neuba-roberta'. Make sure that:

- 'thunlp/neuba-roberta' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'thunlp/neuba-roberta' is the correct path to a directory containing a config.json file

```

Can you please advise?

Best,
Wencong

**Comment by WencongY** [comment]
Hi there, is there an update, please?
